**IMPORTING LIBRARIES**

In [3]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

**LOADING THE DATASET**

In [4]:
dataset = pd.read_csv("/content/loan.csv")

**To view the head of the dataset**

In [5]:
dataset.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

**To view the sum of missing values in each column in the dataset**

In [6]:
dataset.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

**To view the datatypes in dataset**

In [7]:
dataset.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

**To view the whole summary about the dataset**

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

**To selecting the float datatypes in the dataset**

In [11]:
dataset.select_dtypes(include="float64").columns

Index(['CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term',
       'Credit_History'],
      dtype='object')

**From sklearn library import the class which is simpleimputer**

In [12]:
from sklearn.impute import SimpleImputer

**Through SI variable call the simpleimputer**

In [13]:
si=SimpleImputer()

**Through SI class we call the strategy="mean" and through si class we get si.fit_transform()through this we can change the dataset into mean**

In [14]:
si=SimpleImputer(strategy="mean")
si.fit_transform(dataset[['CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term',
       'Credit_History']])

array([[0.00000000e+00, 1.46412162e+02, 3.60000000e+02, 1.00000000e+00],
       [1.50800000e+03, 1.28000000e+02, 3.60000000e+02, 1.00000000e+00],
       [0.00000000e+00, 6.60000000e+01, 3.60000000e+02, 1.00000000e+00],
       ...,
       [2.40000000e+02, 2.53000000e+02, 3.60000000e+02, 1.00000000e+00],
       [0.00000000e+00, 1.87000000e+02, 3.60000000e+02, 1.00000000e+00],
       [0.00000000e+00, 1.33000000e+02, 3.60000000e+02, 0.00000000e+00]])

**Converting the array into dataframe**

In [16]:
si=SimpleImputer(strategy="mean")
ar=si.fit_transform(dataset[['CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term',
       'Credit_History']])

**Through pandas we can view the dataframe**

In [17]:
pd.DataFrame(ar,columns=dataset.select_dtypes(include="float64").columns)

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History
0                  0.0  146.412162             360.0             1.0
1               1508.0  128.000000             360.0             1.0
2                  0.0   66.000000             360.0             1.0
3               2358.0  120.000000             360.0             1.0
4                  0.0  141.000000             360.0             1.0
..                 ...         ...               ...             ...
609                0.0   71.000000             360.0             1.0
610                0.0   40.000000             180.0             1.0
611              240.0  253.000000             360.0             1.0
612                0.0  187.000000             360.0             1.0
613                0.0  133.000000             360.0             0.0

[614 rows x 4 columns]

**Giving the variable name to the dataset**

In [18]:
new_dataset=pd.DataFrame(ar,columns=dataset.select_dtypes(include="float64").columns)

**Viewing missing values in new_dataset**

In [20]:
new_dataset.isnull().sum()

CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
dtype: int64

**Viewing the new dataset**

In [21]:
new_dataset

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History
0                  0.0  146.412162             360.0             1.0
1               1508.0  128.000000             360.0             1.0
2                  0.0   66.000000             360.0             1.0
3               2358.0  120.000000             360.0             1.0
4                  0.0  141.000000             360.0             1.0
..                 ...         ...               ...             ...
609                0.0   71.000000             360.0             1.0
610                0.0   40.000000             180.0             1.0
611              240.0  253.000000             360.0             1.0
612                0.0  187.000000             360.0             1.0
613                0.0  133.000000             360.0             0.0

[614 rows x 4 columns]

**To view the mean of LoanAmount**

In [22]:
dataset["LoanAmount"].mean()

146.41216216216216